export const PLAYER_MAX_VELOCITY = 5;
export const PLAYER_SPEED = 0.4;
export const PLAYER_CONSTANT_SPEED_LOSE = 0.9;
export const PLAYER_VELOCITY_THRESHOLD = 0.3;
export const PLAYER_TIME_BETWEEN_FRAMES_IN_MILLISECONDS = 200;
